### ISSUE TITLE
为什么我无法连接到服务端？

### ISSUE THREAD

**Issue by dxvgef** [hprose/hprose-html5#4]
```Javascript
var server = new hprose.TcpClient('tcp://127.0.0.1:10080', ['hello']);
alert(JSON.stringify(server));
```
server打印出来是一个空对象

**Comment by andot** [comment]
请参考[文档](https://github.com/hprose/hprose-html5/wiki/%E5%AE%A2%E6%88%B7%E7%AB%AF%E7%9A%84%E7%89%B9%E6%AE%8A%E8%AE%BE%E7%BD%AE#hprose-%E7%9A%84-tcp-%E5%AE%A2%E6%88%B7%E7%AB%AF)

> hprose for HTML5 的 TCP 客户端是基于 chrome.sockets.tcp 实现的。因此它只可以在 chrome apps 或基于 ionic/cordova 的 android、iOS 应用中使用。
> 
> 在 ionic/cordova 中使用时，需要安装 cordova-plugin-chrome-apps-sockets-tcp 插件。
>
